### ISSUE TITLE
ODIS11 Rule 05 - wrong path?

### ISSUE THREAD

**Issue by lvoraberger** [cablebender/odisfirewall#1]
`new-netfirewallrule -DisplayName '05 DoIP-Broadcast-Kommunikation zwischen ODIS Service und VAS6154(A)' -Profile @('Private','Public') -Direction Inbound -Action Allow  -Remoteaddres @('255.255.255.255') -program '%ProgramFiles%\Offboard_Diagnostic_Information_System_Service\OffboardDiagLauncher.exe'`

should be 

`new-netfirewallrule -DisplayName '05 DoIP-Broadcast-Kommunikation zwischen ODIS Service und VAS6154(A)' -Profile @('Private','Public') -Direction Inbound -Action Allow  -Remoteaddres @('255.255.255.255') -program '%ProgramFiles%\OS\OffboardDiagLauncher.exe'`

The path `%ProgramFiles%\Offboard_Diagnostic_Information_System_Service\OffboardDiagLauncher.exe` does not exist after ODIS 11 installation

**Comment by cablebender** [comment]
thanks for your hint! :-)
